[tasks.git-submodules-update]
command="git"
args=["submodule", "update", "--remote", "--force", "--rebase", "--init"]

[tasks.cargo-update]
command = "cargo"
args = ["update"]

[tasks.build]
dependencies = ["git-submodules-update"]

[tasks.build-native]
dependencies = ["git-submodules-update"]
command = "cargo"
args = ["build", "--target", ""]

[tasks.build-web]
dependencies = ["git-submodules-update"]
command = "cargo"
args = ["build","--target", "wasm32-unknown-unknown"]