[package]
name = "client-side-encryption"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bucket-client-core = {path="../../" }
[[bin]]
name = "client-side-encryption"
path = "main.rs"
